### ISSUE TITLE
活动启动类

### ISSUE THREAD

**Issue by 738631760** [738631760/-#1]
- 这是一款记录软件启动时，各个不同类的界面，是一款修改软件的神器

![Screenshot_2022-01-24-02-38-03-848_com.x7890.shortcutcreator.jpg](https://user-images.githubusercontent.com/89699420/150693114-45dfd1f8-193f-4043-a6e1-562c3339b654.jpg)![Screenshot_2022-01-24-02-38-31-128_com.x7890.shortcutcreator.jpg](https://user-images.githubusercontent.com/89699420/150693125-e5ac3ac6-6a0e-45da-8095-a8d09cf4a1fb.jpg)![Screenshot_2022-01-24-02-38-46-132_com.x7890.shortcutcreator.jpg](https://user-images.githubusercontent.com/89699420/150693131-24cec6d4-7116-40ca-a139-d39ac3b3dd76.jpg)

`大佬、小白修改破解软件必备神器`

[]()**https://xiezi.lanzoul.com/iJIMDz6i1af**

**Comment by bufanlong** [comment]
蝎子网络弹窗v1.1引流

**Comment by 738631760** [comment]
朱
